# Site settings
title: Rich Lundeen
email: richard.lundeen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writing site with my books
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.richlundeen.com" # the base hostname & protocol for your site
twitter_username: richlundeen
github_username:  webstersprodigy

# Build settings
markdown: kramdown
